"""Add ai_providers models

Revision ID: 94c1914d6c22
Revises: a07f9c6758f1
Create Date: 2026-06-21 20:52:13.207991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c1914d6c22'
down_revision: Union[str, Sequence[str], None] = 'a07f9c6758f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('api_base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_providers_name'), ['name'], unique=True)

    op.create_table('ai_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('model_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('max_input_tokens', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('max_context_window', sa.Integer(), nullable=False),
    sa.Column('default_temperature', sa.Float(), nullable=False),
    sa.Column('default_top_p', sa.Float(), nullable=False),
    sa.Column('default_frequency_penalty', sa.Float(), nullable=False),
    sa.Column('default_presence_penalty', sa.Float(), nullable=False),
    sa.Column('supports_tools', sa.Boolean(), nullable=False),
    sa.Column('supports_parallel_tools', sa.Boolean(), nullable=False),
    sa.Column('supports_structured_output', sa.Boolean(), nullable=False),
    sa.Column('supports_json', sa.Boolean(), nullable=False),
    sa.Column('supports_stream', sa.Boolean(), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('supports_image_generation', sa.Boolean(), nullable=False),
    sa.Column('supports_audio_input', sa.Boolean(), nullable=False),
    sa.Column('supports_audio_output', sa.Boolean(), nullable=False),
    sa.Column('supports_embeddings', sa.Boolean(), nullable=False),
    sa.Column('supports_reasoning', sa.Boolean(), nullable=False),
    sa.Column('supports_system_prompt', sa.Boolean(), nullable=False),
    sa.Column('supports_web_search', sa.Boolean(), nullable=False),
    sa.Column('supports_file_upload', sa.Boolean(), nullable=False),
    sa.Column('supports_pdf', sa.Boolean(), nullable=False),
    sa.Column('supports_function_call', sa.Boolean(), nullable=False),
    sa.Column('supports_seed', sa.Boolean(), nullable=False),
    sa.Column('supports_response_format', sa.Boolean(), nullable=False),
    sa.Column('supports_cache', sa.Boolean(), nullable=False),
    sa.Column('supports_citations', sa.Boolean(), nullable=False),
    sa.Column('supports_multimodal', sa.Boolean(), nullable=False),
    sa.Column('typical_latency_ms', sa.Integer(), nullable=False),
    sa.Column('speed_tier', sa.String(length=50), nullable=False),
    sa.Column('input_price_per_million', sa.Float(), nullable=False),
    sa.Column('output_price_per_million', sa.Float(), nullable=False),
    sa.Column('cache_price_per_million', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('fallback_model_id', sa.UUID(), nullable=True),
    sa.Column('provider_model_name', sa.String(length=100), nullable=True),
    sa.Column('api_version', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fallback_model_id'], ['ai_models.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_models_model_key'), ['model_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_ai_models_provider_id'), ['provider_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_models_provider_id'))
        batch_op.drop_index(batch_op.f('ix_ai_models_model_key'))

    op.drop_table('ai_models')
    with op.batch_alter_table('ai_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_providers_name'))

    op.drop_table('ai_providers')
    # ### end Alembic commands ###
