"""Add file_id to messages

Revision ID: 9dae67163151
Revises: 4beefece491d
Create Date: 2026-07-01 03:12:37.853731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dae67163151'
down_revision: Union[str, Sequence[str], None] = '4beefece491d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_file_id'), ['file_id'], unique=False)
        batch_op.create_foreign_key(None, 'files', ['file_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_file_id'))
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
