from enum import Enum

class ModelCapability(str, Enum):
    """Enumeration of all supported capabilities for AI Models."""
    TOOLS = "tools"
    PARALLEL_TOOLS = "parallel_tools"
    STRUCTURED_OUTPUT = "structured_output"
    JSON = "json"
    STREAM = "stream"
    VISION = "vision"
    IMAGE_GENERATION = "image_generation"
    AUDIO_INPUT = "audio_input"
    AUDIO_OUTPUT = "audio_output"
    EMBEDDINGS = "embeddings"
    REASONING = "reasoning"
    SYSTEM_PROMPT = "system_prompt"
    WEB_SEARCH = "web_search"
    FILE_UPLOAD = "file_upload"
    PDF = "pdf"
    FUNCTION_CALL = "function_call"
    SEED = "seed"
    RESPONSE_FORMAT = "response_format"
    CACHE = "cache"
    CITATIONS = "citations"
    MULTIMODAL = "multimodal"
